version: '3.9'

x-prototype: &prototype
  build:
    context: .
    dockerfile: ./package/prototype/Dockerfile
  volumes:
    - ./src:/src

services:
  
  rabbit:
    image: rabbitmq:management
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  queue:
    <<: *prototype
    command: poetry run python -m at_queue -H rabbit
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: ps -p $(cat /var/run/at_queue/pidfile.pid) || exit 1
      interval: 1s
      timeout: 3s
      retries: 30
    
  solver:
    <<: *prototype
    container_name: solver
    command: poetry run python -m at_solver -H rabbit
    depends_on:
      queue:
        condition: service_healthy
    healthcheck:
      test: ps -p $(cat /var/run/at_solver/pidfile.pid) || exit 1
      interval: 1s
      timeout: 3s
      retries: 30

  temporal_solver:
    <<: *prototype
    container_name: temporal_solver
    command: poetry run python -m at_temporal_solver -H rabbit
    depends_on:
      queue:
        condition: service_healthy
    healthcheck:
      test: ps -p $(cat /var/run/at_temporal_solver/pidfile.pid) || exit 1
      interval: 1s
      timeout: 3s
      retries: 30

  simulation:
    <<: *prototype
    container_name: simulation
    command: poetry run python -m at_simulation_mocking -H rabbit
    depends_on:
      queue:
        condition: service_healthy
    healthcheck:
      test: ps -p $(cat /var/run/at_simulation_mocking/pidfile.pid) || exit 1
      interval: 1s
      timeout: 3s
      retries: 30

  blackboard:
    <<: *prototype
    container_name: blackboard
    command: poetry run python -m at_blackboard -H rabbit
    depends_on:
      queue:
        condition: service_healthy
    healthcheck:
      test: ps -p $(cat /var/run/at_blackboard/pidfile.pid) || exit 1
      interval: 1s
      timeout: 3s
      retries: 30

  joint:
    <<: *prototype
    container_name: joint
    command: poetry run python -m at_joint -H rabbit
    depends_on:
      queue:
        condition: service_healthy
    healthcheck:
      test: ps -p $(cat /var/run/at_joint/pidfile.pid) || exit 1
      interval: 1s
      timeout: 3s
      retries: 30
    
  configurator:
    <<: *prototype
    command: poetry run python -m at_configurator -H rabbit -c /src/config.yaml
    depends_on:
      solver:
        condition: service_healthy
      temporal_solver:
        condition: service_healthy
      simulation:
        condition: service_healthy
      blackboard:
        condition: service_healthy
      joint:
        condition: service_healthy

  joint_debugger:
    <<: *prototype
    container_name: joint_debugger
    command: poetry run python -m at_joint --debugger -H rabbit -dh 0.0.0.0
    depends_on:
      joint:
        condition: service_healthy
    healthcheck:
      test: ps -p $(cat /var/run/at_joint_debugger/pidfile.pid) || exit 1
      interval: 1s
      timeout: 3s
      retries: 30

  nginx:
    build: ./package/nginx
    ports:
      - 8000:8000
    depends_on:
      joint_debugger:
        condition: service_healthy
    expose:
      - 8000

  
  
  