auth_token: default
config:
  ATSolver:
    kb:
      path: /src/TrafficAccidentsKB.kbs
  ATTemporalSolver:
    kb:
      path: /src/TrafficAccidentsKB.kbs
  ATSimulationMocking:
    sm_run:
      path: /src/ResourceParameters.xml
  ATJoint:
    at_simulation: ATSimulationMocking
    at_simulation_file: 1